version: '3.8'

services:
  veiculooo:
    build: .
    container_name: veiculooo
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email SEU_EMAIL@EXEMPLO.COM --agree-tos --no-eff-email --force-renewal -d veicul.ooo -d www.veicul.ooo

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  web:
    driver: bridge
